version: 0.0
Resources:
  - FetchMessagesLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: fetchMessages
        Alias: nonprod
        CurrentVersion: 1
        TargetVersion: 2
        Functions:
          - BeforeAllowTraffic: validateFunction
          - AfterAllowTraffic: notifySuccess

  - StoreMessagesLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: storeMessages
        Alias: nonprod
        CurrentVersion: 3
        TargetVersion: 4
        Functions:
          - BeforeAllowTraffic: checkDependencies
          - AfterAllowTraffic: cleanupResources

  - DeleteMessagesLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: deleteMessages
        Alias: nonprod
        CurrentVersion: 3
        TargetVersion: 4
        Functions:
          - BeforeAllowTraffic: checkDependencies
          - AfterAllowTraffic: cleanupResources