version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20 # Specify your required Node.js version
    commands:
      - echo "Installing dependencies..."
      - pip install awscli # Using pip to install AWS CLI
  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # Install dependencies and prepare Lambda functions
      - cd lambda-handlers/fetchMessages && npm install && cd ../..
      - cd lambda-handlers/storeMessages && npm install && cd ../..
  build:
    commands:
      - echo "Building and packaging Lambda functions..."
      # Zip Lambda functions
      - cd lambda-handlers/fetchMessages && zip -r ../../fetchMessages.zip . && cd ../..
      - cd lambda-handlers/storeMessages && zip -r ../../storeMessages.zip . && cd ../..
  post_build:
    commands:
      - echo "Uploading deployment artifacts to S3..."
      - aws s3 cp fetchMessages.zip s3://notifications-app-pipeline/fetchMessages.zip
      - aws s3 cp storeMessages.zip s3://notifications-app-pipeline/storeMessages.zip
artifacts:
  files:
    - fetchMessages.zip
    - storeMessages.zip
  discard-paths: yes